// Question banks for all IceBreak games
// Large enough to avoid repeating within many sessions

// ─── Would You Rather (100 dilemmas) ─────────────────────────────────────────
export const WYR_QUESTIONS: Array<{ a: string; b: string }> = [
  { a: 'Always be 10 minutes late', b: 'Always be 20 minutes early' },
  { a: 'Work from a beach with slow Wi-Fi', b: 'Work from a windowless office with blazing-fast internet' },
  { a: 'Never use social media again', b: 'Give up coffee and tea forever' },
  { a: 'Have a rewind button for your life', b: 'Have a pause button for your life' },
  { a: 'Only be able to whisper', b: 'Only be able to shout' },
  { a: 'Know when you will die', b: 'Know how you will die' },
  { a: 'Have unlimited money but zero free time', b: 'Have unlimited free time but barely enough money' },
  { a: 'Know every language', b: 'Play every musical instrument' },
  { a: 'Travel to the past', b: 'Travel to the future' },
  { a: 'Live in a world without music', b: 'Live in a world without movies' },
  { a: 'Always have to say exactly what you think', b: 'Never be able to speak your true opinion' },
  { a: 'Be world-famous but miserable', b: 'Be totally unknown but happy' },
  { a: 'Have the ability to fly', b: 'Have the ability to be invisible' },
  { a: 'Never age physically', b: 'Never age mentally' },
  { a: 'Lose all your memories', b: 'Lose your ability to make new memories' },
  { a: 'Always feel slightly cold', b: 'Always feel slightly hot' },
  { a: 'No internet for a month', b: 'No food delivery for a year' },
  { a: 'Read everyone\'s thoughts', b: 'Have no one able to read yours' },
  { a: 'Only ever eat your favourite food', b: 'Never eat your favourite food again' },
  { a: 'Give up Netflix', b: 'Give up Spotify' },
  { a: 'Wake up as a different person every day', b: 'Stay exactly as you are forever' },
  { a: 'Have a photographic memory', b: 'Be able to forget anything on demand' },
  { a: 'Never eat sugar again', b: 'Never eat salt again' },
  { a: 'Be the funniest person in the room', b: 'Be the smartest person in the room' },
  { a: 'Speak in rhymes forever', b: 'Sing everything you say' },
  { a: 'Have a job you hate that makes you rich', b: 'Have a job you love that barely pays' },
  { a: 'Go without your phone for a year', b: 'Go without your laptop for a year' },
  { a: 'Always be the first to arrive anywhere', b: 'Always be the last to leave' },
  { a: 'Have a personal chef', b: 'Have a personal trainer' },
  { a: 'Never need to sleep', b: 'Never need to eat' },
  { a: 'Know the answer to every question', b: 'Know what everyone around you is feeling' },
  { a: 'Lose your sense of taste', b: 'Lose your sense of smell' },
  { a: 'Teleport anywhere instantly', b: 'Time-travel once' },
  { a: 'Have 10 close friends', b: 'Have 1,000 acquaintances' },
  { a: 'Always arrive early', b: 'Always leave last' },
  { a: 'Go to space once', b: 'Go to the bottom of the ocean once' },
  { a: 'Live in a different country every year', b: 'Never leave your home city' },
  { a: 'Meet your future self', b: 'Meet your past self' },
  { a: 'Only communicate via text', b: 'Only communicate via voice calls' },
  { a: 'Have a superpower you must keep secret', b: 'Have no superpower but everyone thinks you do' },
  { a: 'Eat only savoury food forever', b: 'Eat only sweet food forever' },
  { a: 'Always be overdressed', b: 'Always be underdressed' },
  { a: 'Have five siblings', b: 'Be an only child' },
  { a: 'Work four 10-hour days', b: 'Work five 8-hour days' },
  { a: 'Run a marathon with no training', b: 'Swim 5 km with no training' },
  { a: 'Never watch TV again', b: 'Never read books again' },
  { a: 'Have a private jet', b: 'Have a private yacht' },
  { a: 'Lose your wallet', b: 'Lose your phone' },
  { a: 'Always feel slightly cold', b: 'Always feel slightly hungry' },
  { a: 'Be known for one incredible thing', b: 'Be known for being consistently great at everything' },
  { a: 'Live to 100 in average health', b: 'Live to 60 in perfect health' },
  { a: 'Have perfect skin forever', b: 'Have perfect hair forever' },
  { a: 'Work completely alone', b: 'Always work in a team' },
  { a: 'Own a tiny house in an amazing location', b: 'Own a huge house in a remote location' },
  { a: 'Always be running late', b: 'Always have to wait for others' },
  { a: 'Have a talking dog', b: 'Have a talking cat' },
  { a: 'Write one song that becomes a global hit', b: 'Write a book that changes one person\'s life' },
  { a: 'Win an Olympic gold medal', b: 'Win a Nobel Prize' },
  { a: 'Only eat food you cooked yourself', b: 'Only eat food cooked by others' },
  { a: 'Be a genius with no social skills', b: 'Be socially brilliant but average intelligence' },
  { a: 'Have an extra hour in every day', b: 'Need one fewer hour of sleep per night' },
  { a: 'Live where everyone is always honest', b: 'Live where everyone is always kind' },
  { a: 'Know every historical fact', b: 'Know everything that will happen in the next 10 years' },
  { a: 'Give up video games forever', b: 'Give up board games forever' },
  { a: 'Always have background music in your life', b: 'Live in complete silence forever' },
  { a: 'Work from home forever', b: 'Work in an office forever' },
  { a: 'Have a robot assistant', b: 'Have a human personal assistant' },
  { a: 'Age in reverse', b: 'Stop ageing at exactly your current age' },
  { a: 'Run at 60 km/h', b: 'Jump 10 metres high' },
  { a: 'Celebrity status in your field', b: 'Total anonymity in your field' },
  { a: 'Remember every dream you\'ve ever had', b: 'Never dream again' },
  { a: 'Be the best at one sport', b: 'Be good at every sport' },
  { a: 'Never feel embarrassed again', b: 'Never feel bored again' },
  { a: 'Always know the right thing to say', b: 'Always know the right thing to do' },
  { a: 'Have the power to heal others', b: 'Have the power to protect others from harm' },
  { a: 'Speak only in questions for a week', b: 'Communicate only through emojis for a week' },
  { a: 'Own a bakery', b: 'Own a bookshop' },
  { a: 'Have a clone of yourself', b: 'Have a robot version of yourself' },
  { a: 'Always know if someone is lying', b: 'Always be believed no matter what you say' },
  { a: 'Be able to breathe underwater', b: 'Be able to survive in space without a suit' },
  { a: 'Give up meat', b: 'Give up dairy — forever' },
  { a: 'Never have to commute again', b: 'Never have to do chores again' },
  { a: 'Have the ability to pause time', b: 'Have the ability to rewind 5 minutes' },
  { a: 'Always win arguments', b: 'Always be able to end arguments instantly' },
  { a: 'Have a perfect memory for faces', b: 'Have a perfect memory for names' },
  { a: 'Travel business class for free', b: 'Stay in 5-star hotels for free' },
  { a: 'Give up alcohol forever', b: 'Give up junk food forever' },
  { a: 'Be able to read 5× faster', b: 'Be able to type 5× faster' },
  { a: 'Have free broadband forever', b: 'Have free public transport forever' },
  { a: 'Be the first person on Mars', b: 'Be the deepest person underwater ever' },
  { a: 'Have a photographic memory for numbers', b: 'Have a perfect sense of direction always' },
  { a: 'Never have to pay for food again', b: 'Never have to pay for travel again' },
  { a: 'Have 100 million followers with nothing to say', b: 'Have 100 followers hanging on every word' },
  { a: 'Forget every bad memory', b: 'Relive every great memory in vivid detail' },
  { a: 'Have a job that only takes 2 hours a day', b: 'Have a job you find completely fulfilling but demanding' },
  { a: 'Always be slightly overdressed', b: 'Always be slightly underdressed' },
  { a: 'Never feel cold', b: 'Never feel heat' },
  { a: 'Live on a houseboat', b: 'Live in a cabin in the woods' },
  { a: 'Be fluent in 10 languages but tone-deaf', b: 'Be a world-class musician who can only speak one language' },
  { a: 'Have unlimited energy all day', b: 'Only need 4 hours of sleep but wake naturally refreshed' },
]

// ─── This or That (100 binary preferences) ───────────────────────────────────
export const THIS_OR_THAT: Array<{ a: string; b: string }> = [
  { a: 'Coffee', b: 'Tea' },
  { a: 'Morning person', b: 'Night owl' },
  { a: 'iOS', b: 'Android' },
  { a: 'Mountains', b: 'Beach' },
  { a: 'Summer', b: 'Winter' },
  { a: 'Books', b: 'Podcasts' },
  { a: 'Sweet', b: 'Savoury' },
  { a: 'City', b: 'Countryside' },
  { a: 'Dogs', b: 'Cats' },
  { a: 'Call', b: 'Text' },
  { a: 'Netflix', b: 'YouTube' },
  { a: 'Cooking at home', b: 'Eating out' },
  { a: 'Planner', b: 'Go with the flow' },
  { a: 'Hot coffee', b: 'Iced coffee' },
  { a: 'Working out alone', b: 'Group fitness class' },
  { a: 'Science fiction', b: 'Fantasy' },
  { a: 'Rock music', b: 'Pop music' },
  { a: 'Headphones', b: 'Earbuds' },
  { a: 'Dark mode', b: 'Light mode' },
  { a: 'Running', b: 'Swimming' },
  { a: 'Beer', b: 'Wine' },
  { a: 'Thriller', b: 'Comedy' },
  { a: 'Reading', b: 'Watching TV' },
  { a: 'Sunrise', b: 'Sunset' },
  { a: 'Pizza', b: 'Burgers' },
  { a: 'Instagram', b: 'Twitter / X' },
  { a: 'Museum', b: 'Theme park' },
  { a: 'Train', b: 'Plane (short trips)' },
  { a: 'Gym', b: 'Yoga' },
  { a: 'Sweet breakfast', b: 'Savoury breakfast' },
  { a: 'Horror films', b: 'Romance films' },
  { a: 'Hiking', b: 'Cycling' },
  { a: 'Working in silence', b: 'Background noise while working' },
  { a: 'Spending', b: 'Saving' },
  { a: 'Solo travel', b: 'Group travel' },
  { a: 'Mac', b: 'PC' },
  { a: 'Typing', b: 'Handwriting' },
  { a: 'Spicy food', b: 'Mild food' },
  { a: 'Adventure', b: 'Comfort' },
  { a: 'Live in the moment', b: 'Plan ahead' },
  { a: 'Watch sports', b: 'Play sports' },
  { a: 'Art', b: 'Music' },
  { a: 'Physical books', b: 'E-reader' },
  { a: 'Road trip', b: 'Flight (even for short distances)' },
  { a: 'Fast food', b: 'Slow food' },
  { a: 'City breaks', b: 'Long beach holidays' },
  { a: 'Working late', b: 'Starting early' },
  { a: 'New experiences', b: 'Familiar favourites' },
  { a: 'Chocolate', b: 'Vanilla' },
  { a: 'Sea swimming', b: 'Pool swimming' },
  { a: 'Watching the game live', b: 'Watching at home' },
  { a: 'Single-player games', b: 'Multiplayer games' },
  { a: 'Meal prep for the week', b: 'Decide what to eat day-by-day' },
  { a: 'Journalling', b: 'Meditating' },
  { a: 'Comedy series', b: 'Drama series' },
  { a: 'Historical fiction', b: 'Contemporary fiction' },
  { a: 'Morning shower', b: 'Night shower' },
  { a: 'Messy desk', b: 'Perfectly clean desk' },
  { a: 'All-inclusive holiday', b: 'Self-planned trip' },
  { a: 'Indian food', b: 'Italian food' },
  { a: 'Loud party', b: 'Small quiet gathering' },
  { a: 'Virtual meetings', b: 'In-person meetings' },
  { a: 'Short walks often', b: 'Long hikes occasionally' },
  { a: 'Reply instantly', b: 'Reply when you\'re ready' },
  { a: 'Art gallery', b: 'Science museum' },
  { a: 'Minimalist décor', b: 'Maximalist décor' },
  { a: 'Learn a new language', b: 'Learn a new instrument' },
  { a: 'Physical exercise', b: 'Mental exercise' },
  { a: 'Morning workout', b: 'Evening workout' },
  { a: 'Animated films', b: 'Live-action films' },
  { a: 'Deep conversations', b: 'Fun small talk' },
  { a: 'Ocean', b: 'Forest' },
  { a: 'Digital notes', b: 'Paper notebook' },
  { a: 'Fiction', b: 'Non-fiction' },
  { a: 'Bold colours', b: 'Neutral tones' },
  { a: 'Standing desk', b: 'Sitting desk' },
  { a: 'Photography', b: 'Videography' },
  { a: 'Bread as a staple', b: 'Rice as a staple' },
  { a: 'Theatre', b: 'Cinema' },
  { a: 'Warm climate', b: 'Cool climate' },
  { a: 'Night market', b: 'Farmer\'s market' },
  { a: 'Solo project', b: 'Collaborative project' },
  { a: 'Public transport', b: 'Own vehicle' },
  { a: 'Quiet café to work', b: 'Busy café to work' },
  { a: 'Long weekend', b: 'Extra day off mid-week' },
  { a: 'Tea with milk', b: 'Tea without milk' },
  { a: 'Salty snacks', b: 'Sweet snacks' },
  { a: 'Comedy podcasts', b: 'True crime podcasts' },
  { a: 'Always on time', b: 'Fashionably late' },
  { a: 'Declutter often', b: 'Keep everything just in case' },
  { a: 'Office plants', b: 'No plants' },
  { a: 'Window seat', b: 'Aisle seat' },
  { a: 'Leftovers for lunch', b: 'Fresh food every day' },
  { a: 'Cooking with music', b: 'Cooking in silence' },
  { a: 'Formal wear', b: 'Smart casual always' },
  { a: 'Print photos', b: 'Keep photos digital' },
  { a: 'Evening person', b: 'Afternoon person' },
  { a: 'Go to the gym', b: 'Work out at home' },
]

// ─── Finish the Sentence (30 prompts) ────────────────────────────────────────
export const FINISH_THE_SENTENCE_PROMPTS: string[] = [
  'People are always surprised to learn I...',
  'The most random skill I have is...',
  'My biggest unpopular opinion is...',
  'If I weren\'t in this job I would be...',
  'The thing I pretend to understand but don\'t is...',
  'My secret talent that nobody here knows is...',
  'I\'m way too competitive about...',
  'The weirdest thing on my bucket list is...',
  'Something I wish I could tell my younger self is...',
  'The app I spend embarrassingly too much time on is...',
  'My most ridiculous fear is...',
  'I used to be obsessed with...',
  'The worst advice I ever followed was...',
  'One thing I\'ve never admitted to a colleague is...',
  'If I had a superpower it would be...',
  'The hobby I keep meaning to pick up is...',
  'My go-to comfort food at midnight is...',
  'I always get irrationally annoyed when...',
  'Something I was terrible at as a kid that I\'m now good at is...',
  'The strangest job I\'ve ever had or wanted was...',
  'If I could instantly become an expert in something it would be...',
  'I\'ve never admitted it but I actually enjoy...',
  'The most embarrassing song in my playlist is...',
  'If I were a superhero my weakness would be...',
  'I will always choose ... over sleep',
  'When no one\'s watching I always...',
  'The show I watched start to finish in one sitting was...',
  'The most niche thing I\'m actually an expert in is...',
  'The opinion I hold that most people disagree with is...',
  'A fact about me that sounds made up but is completely true is...',
]

// ─── Who in the Room — "Most likely to..." (60 prompts) ──────────────────────
export const WHO_IN_THE_ROOM_PROMPTS: string[] = [
  'Most likely to become famous',
  'Most likely to be the last person standing at a party',
  'Most likely to go off-grid for a year',
  'Most likely to have an unusual hidden hobby',
  'Most likely to write a book someday',
  'Most likely to start their own business',
  'Most likely to accidentally start a rumour',
  'Most likely to survive in the wild',
  'Most likely to know a celebrity personally',
  'Most likely to move to another country',
  'Most likely to become a professional athlete — later in life',
  'Most likely to still be working at 75',
  'Most likely to cry at a film',
  'Most likely to have an unpublished masterpiece',
  'Most likely to become a chef',
  'Most likely to appear on a reality TV show',
  'Most likely to win a pub quiz',
  'Most likely to have a secret talent no one suspects',
  'Most likely to befriend a stranger in 5 minutes',
  'Most likely to have the most unusual morning routine',
  'Most likely to have too many browser tabs open',
  'Most likely to send emails at 2am',
  'Most likely to be the first to leave the office',
  'Most likely to pretend to be ill to get a day off',
  'Most likely to accidentally message the wrong person',
  'Most likely to always be late',
  'Most likely to give the best life advice',
  'Most likely to know a random trivia answer',
  'Most likely to turn a 5-minute task into a 2-hour project',
  'Most likely to be the most organised person you\'ve ever met',
  'Most likely to have a side hustle',
  'Most likely to bring homemade food to the office',
  'Most likely to read the manual before using something',
  'Most likely to work through lunch',
  'Most likely to have the best travel stories',
  'Most likely to panic before a deadline and still somehow deliver',
  'Most likely to be the person everyone calls for help',
  'Most likely to be on first-name terms with every barista in town',
  'Most likely to forget their password',
  'Most likely to binge-watch a series in one weekend',
  'Most likely to know every lyric to a song from 20 years ago',
  'Most likely to turn a hobby into a business',
  'Most likely to wake up voluntarily before 5am',
  'Most likely to break a world record one day',
  'Most likely to spend hours choosing the perfect playlist',
  'Most likely to be the last to hear any news',
  'Most likely to go viral on social media',
  'Most likely to become a life coach',
  'Most likely to give the most brutally honest feedback',
  'Most likely to remember everyone\'s birthday without being reminded',
  'Most likely to still be using their 5-year-old phone',
  'Most likely to have read every book on the bestseller list',
  'Most likely to try any new technology on day one',
  'Most likely to run entirely on coffee',
  'Most likely to turn down a promotion for better work-life balance',
  'Most likely to have a full superhero alter ego planned out',
  'Most likely to accidentally buy something very expensive online',
  'Most likely to be CEO of something in 10 years',
  'Most likely to adopt every stray animal they see',
  'Most likely to have the most interesting story about how they got here',
]
